version: '3'
services:
  manage-hotel:
    image: manage-hotel:latest
    container_name: manage-hotel
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.env:/manage-hotel/.env
    networks:
      - mongo_network
networks:
  mongo_network:
    name: mongo_default
    external: true
